# Generated by Django 5.0.7 on 2024-08-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='cms.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='cms.tag'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='masteredata',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='poojas',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
