# Generated by Django 5.0.7 on 2024-08-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
